# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      # Cancel building pull requests when new commits are pushed
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ]; then
          echo "Cancelling build for external version"
          exit 183
        fi

# Python configuration
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

# Search settings
search:
  ranking:
    api-reference.md: 10
    quickstart.md: 9
    configuration.md: 8
  ignore:
    - development.md
