# Generated by Django 5.2.11 on 2026-02-18 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organization name (must be unique across system)', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier for organization', max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether organization is active')),
                ('max_devices', models.PositiveIntegerField(blank=True, help_text='Device limit for this organization (null = unlimited)', null=True)),
                ('subscription_tier', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='basic', help_text='Subscription/feature tier', max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Organization logo for branded UI', null=True, upload_to='org_logos/')),
                ('primary_color', models.CharField(default='#007bff', help_text='Primary brand color (hex format)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_contact', models.ForeignKey(blank=True, help_text='Primary contact/admin for this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_contact_for_orgs', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, help_text='Django site this organization belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campus name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe identifier (unique within org)', max_length=200)),
                ('address', models.TextField(blank=True, help_text='Physical address of campus')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='USA', max_length=100)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone identifier', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether campus is active')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about campus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='Parent organization', on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='micboard_multitenancy.organization')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer - Read-only access'), ('operator', 'Operator - Can modify device assignments'), ('admin', 'Admin - Full access except billing'), ('owner', 'Owner - Full access including billing')], default='viewer', help_text="User's permission level in organization", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether membership is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, help_text='Optional: Limit user to specific campus only', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='micboard_multitenancy.campus')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this membership', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization user has access to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='micboard_multitenancy.organization')),
                ('user', models.ForeignKey(help_text='User with access to organization', on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
                'ordering': ['organization', 'user'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='micboard_mu_slug_02ede1_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['site', 'is_active'], name='micboard_mu_site_id_e1c041_idx'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['organization', 'is_active'], name='micboard_mu_organiz_92504f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'is_active'], name='micboard_mu_user_id_044365_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'is_active'], name='micboard_mu_organiz_e423e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('user', 'organization')},
        ),
    ]
