# High-level functional API (backwards-compatible helpers)
from .compat import (
    serialize_assignment,
    serialize_assignments,
    serialize_channel,
    serialize_charger,
    serialize_charger_detail,
    serialize_charger_summary,
    serialize_chargers,
    serialize_connection,
    serialize_connections,
    serialize_discovered_device,
    serialize_group,
    serialize_location,
    serialize_locations,
    serialize_receiver,
    serialize_receiver_detail,
    serialize_receiver_summary,
    serialize_receivers,
    serialize_transmitter,
)
from .serializers import (
    ChannelSerializer,
    ChargerDetailSerializer,
    ChargerSlotSerializer,
    ChargerSummarySerializer,
    DeviceAssignmentSerializer,
    DiscoveredDeviceSerializer,
    GroupSerializer,
    ReceiverDetailSerializer,
    ReceiverSummarySerializer,
    TransmitterSerializer,
)

__all__ = [
    # DRF serializer classes
    "ChannelSerializer",
    "ChargerDetailSerializer",
    "ChargerSlotSerializer",
    "ChargerSummarySerializer",
    "DeviceAssignmentSerializer",
    "DiscoveredDeviceSerializer",
    "GroupSerializer",
    "ReceiverDetailSerializer",
    "ReceiverSummarySerializer",
    "TransmitterSerializer",
    # Functional helpers
    "serialize_assignment",
    "serialize_assignments",
    "serialize_channel",
    "serialize_charger",
    "serialize_charger_detail",
    "serialize_charger_summary",
    "serialize_chargers",
    "serialize_connection",
    "serialize_connections",
    "serialize_discovered_device",
    "serialize_group",
    "serialize_location",
    "serialize_locations",
    "serialize_receiver",
    "serialize_receiver_detail",
    "serialize_receiver_summary",
    "serialize_receivers",
    "serialize_transmitter",
]
