#!/usr/bin/env python3
# ruff: noqa: S603, S607, T201
"""Reject edits to migration history and validate newly generated migrations."""

from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path

MIGRATION_PATH = re.compile(r"(?:^|/)migrations/\d+_[^/]+\.py$")
GENERATED_HEADER = re.compile(r"^# Generated by Django \S+ on \d{4}-\d{2}-\d{2} ")
MIGRATION_CLASS = "class Migration(migrations.Migration):"


def git_paths(*args: str) -> set[Path]:
    """Return NUL-delimited paths from a read-only git query."""
    result = subprocess.run(
        ["git", *args, "-z"],
        check=True,
        capture_output=True,
        text=True,
    )
    return {Path(path) for path in result.stdout.split("\0") if path}


def migration_paths(paths: set[Path]) -> set[Path]:
    """Keep numbered Python migration files only."""
    return {path for path in paths if MIGRATION_PATH.search(path.as_posix())}


def pull_request_diff(*, diff_filter: str) -> set[Path]:
    """Return paths changed by the pull request when running in GitHub Actions."""
    base_ref = os.environ.get("GITHUB_BASE_REF")
    if not base_ref:
        return set()
    return git_paths(
        "diff",
        "--name-only",
        f"--diff-filter={diff_filter}",
        f"origin/{base_ref}...HEAD",
    )


def main() -> int:
    """Validate migration history and return a process exit status."""
    changed_history = migration_paths(
        git_paths("diff", "--name-only", "--diff-filter=MD")
        | git_paths("diff", "--cached", "--name-only", "--diff-filter=MD")
        | pull_request_diff(diff_filter="MD")
    )
    if changed_history:
        print("Existing migration files are immutable; generate a new migration instead:")
        for path in sorted(changed_history):
            print(f"  {path}")
        return 1

    new_migrations = migration_paths(
        git_paths("diff", "--name-only", "--diff-filter=A")
        | git_paths("diff", "--cached", "--name-only", "--diff-filter=A")
        | git_paths("ls-files", "--others", "--exclude-standard")
        | pull_request_diff(diff_filter="A")
    )
    errors: list[str] = []
    for path in sorted(new_migrations):
        try:
            content = path.read_text()
        except OSError as exc:
            errors.append(f"{path}: cannot read generated migration: {exc}")
            continue
        first_line = content.splitlines()[0] if content else ""
        if not GENERATED_HEADER.match(first_line):
            errors.append(f"{path}: missing Django-generated header")
        if MIGRATION_CLASS not in content:
            errors.append(f"{path}: missing Django Migration class")

    if errors:
        print("New migrations must be created by Django's makemigrations command:")
        for error in errors:
            print(f"  {error}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
