#!/usr/bin/env python3
# ruff: noqa: T201
"""Generate the Python API reference Markdown consumed by the documentation site.

Griffe parses the ``micboard`` package statically, so the documentation build never
imports Django or needs ``DJANGO_SETTINGS_MODULE``. The emitted Markdown is committed
to ``docs/api/reference/`` so that ``just docs`` stays a single-step build; regenerate
it with ``just docs-api`` whenever the documented modules change.
"""

from __future__ import annotations

import argparse
from collections.abc import Iterable, Iterator
from dataclasses import dataclass
from pathlib import Path

import griffe

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "docs" / "api" / "reference"
SOURCE_URL = "https://github.com/justprosound/django-micboard/blob/main"
GENERATED_MARKER = "<!-- Generated by scripts/generate_api_docs.py. Do not edit by hand. -->"


@dataclass(frozen=True)
class Page:
    """A generated reference page and the modules it documents."""

    slug: str
    title: str
    description: str
    modules: tuple[str, ...]


# The documented surface is deliberately curated: it mirrors the integration contract
# described in docs/development/api-reference.md rather than every internal module.
PAGES: tuple[Page, ...] = (
    Page(
        slug="models",
        title="Models",
        description=(
            "Django model domains, managers, and querysets. Import each model from its "
            "defining domain module; the `micboard.models` package intentionally does not "
            "re-export model classes."
        ),
        modules=(
            "micboard.models.hardware",
            "micboard.models.monitoring",
            "micboard.models.locations",
            "micboard.models.settings",
            "micboard.models.telemetry",
            "micboard.models.discovery",
            "micboard.models.realtime",
            "micboard.models.rf_coordination",
            "micboard.models.users",
            "micboard.models.audit",
            "micboard.models.band_plans",
            "micboard.models.device_specs",
            "micboard.models.integrations",
            "micboard.models.base_managers",
            "micboard.models.mixins",
        ),
    ),
    Page(
        slug="services",
        title="Services",
        description=(
            "The typed service layer is the supported write path. Services own business "
            "logic, enforce object scope, and accept Pydantic command objects."
        ),
        modules=(
            "micboard.services.core.hardware",
            "micboard.services.core.hardware_lifecycle",
            "micboard.services.core.hardware_sync",
            "micboard.services.core.performer_assignment",
            "micboard.services.core.performer_assignment_dtos",
            "micboard.services.core.device_metadata",
            "micboard.services.core.device_specs",
            "micboard.services.core.user_profile",
            "micboard.services.settings.settings_service",
            "micboard.services.settings.browser_refresh_service",
            "micboard.services.settings.registry",
            "micboard.services.settings.dtos",
            "micboard.services.shared.access_policy",
            "micboard.services.shared.base_dto",
            "micboard.services.common.base.plugin",
            "micboard.services.common.base.device_normalizer",
            "micboard.services.common.base.client",
            "micboard.services.common.base.resilience",
            "micboard.services.common.base.rate_limiter",
            "micboard.services.common.base.circuit_breaker",
        ),
    ),
    Page(
        slug="management-commands",
        title="Management Commands",
        description=(
            "Management commands are thin wrappers that delegate to the service layer. "
            "Run them with `uv run --no-sync python manage.py <command>`."
        ),
        modules=("micboard.management",),
    ),
    Page(
        slug="websocket-consumers",
        title="WebSocket Consumers",
        description=(
            "Authenticated Channels consumers that fan real-time device updates out to "
            "browsers. See [WebSocket API](../websocket.md) for the message contract."
        ),
        modules=(
            "micboard.websockets.consumers",
            "micboard.websockets.authorization",
            "micboard.websockets.routing",
        ),
    ),
    Page(
        slug="exceptions",
        title="Exceptions",
        description=(
            "The consolidated exception hierarchy raised by services and integrations "
            "(see [ADR-009](../../adr/009-consolidate-exception-hierarchy.md))."
        ),
        modules=("micboard.exceptions",),
    ),
)

SECTION_HEADINGS = {
    griffe.DocstringSectionKind.parameters: "Parameters",
    griffe.DocstringSectionKind.other_parameters: "Other parameters",
    griffe.DocstringSectionKind.attributes: "Attributes",
    griffe.DocstringSectionKind.raises: "Raises",
    griffe.DocstringSectionKind.warns: "Warns",
    griffe.DocstringSectionKind.returns: "Returns",
    griffe.DocstringSectionKind.yields: "Yields",
    griffe.DocstringSectionKind.receives: "Receives",
}
VARIADIC_KINDS = (griffe.ParameterKind.var_positional, griffe.ParameterKind.var_keyword)


def load_package() -> griffe.Module:
    """Load ``micboard`` statically, without importing Django."""
    package = griffe.load(
        "micboard",
        search_paths=[ROOT],
        docstring_parser="google",
        allow_inspection=False,
        store_source=False,
    )
    if not isinstance(package, griffe.Module):
        raise TypeError("expected micboard to load as a module")
    return package


def resolve(package: griffe.Module, path: str) -> griffe.Module:
    """Return the module object for a dotted module path below ``micboard``."""
    current: griffe.Object | griffe.Alias = package
    for part in path.split(".")[1:]:
        current = current.members[part]
        if isinstance(current, griffe.Alias):
            current = current.final_target
    if not isinstance(current, griffe.Module):
        raise TypeError(f"{path} is not a module")
    return current


def source_link(obj: griffe.Object) -> str | None:
    """Return a Markdown link to the object's definition on GitHub."""
    filepath = obj.filepath
    if isinstance(filepath, list):  # namespace packages expose several paths
        filepath = filepath[0] if filepath else None
    if filepath is None:
        return None
    try:
        relative = Path(filepath).resolve().relative_to(ROOT)
    except ValueError:
        return None
    anchor = f"#L{obj.lineno}" if obj.lineno else ""
    return f"[Source]({SOURCE_URL}/{relative.as_posix()}{anchor})"


def documentable(obj: griffe.Object) -> bool:
    """Return whether an object carries enough information to be worth rendering."""
    if isinstance(obj, griffe.Class):
        # Conditional import stubs are empty classes with no docstring; skip them.
        return obj.docstring is not None or bool(members(obj))
    if isinstance(obj, griffe.Attribute):
        return obj.docstring is not None
    return True


def members(obj: griffe.Object) -> list[griffe.Object]:
    """Return renderable members of an object, in source order."""
    selected = [
        member
        for member in obj.members.values()
        if not member.name.startswith("_")
        and not member.is_alias
        and isinstance(member, griffe.Object)
        and not isinstance(member, griffe.Module)
        and documentable(member)
    ]
    return sorted(selected, key=lambda member: member.lineno or 0)


def signature(func: griffe.Function) -> str:
    """Render a call signature from griffe parameter metadata."""
    rendered: list[str] = []
    for parameter in func.parameters:
        if parameter.name in {"self", "cls"}:
            continue
        kind = parameter.kind or griffe.ParameterKind.positional_or_keyword
        prefix = {
            griffe.ParameterKind.var_positional: "*",
            griffe.ParameterKind.var_keyword: "**",
        }.get(kind, "")
        text = f"{prefix}{parameter.name}"
        if parameter.annotation is not None:
            text += f": {parameter.annotation}"
        if parameter.default is not None and kind not in VARIADIC_KINDS:
            text += f" = {parameter.default}"
        rendered.append(text)
    returns = f" -> {func.returns}" if func.returns is not None else ""
    return f"({', '.join(rendered)}){returns}"


def quoted(text: str) -> str:
    """Render multi-line text as a Markdown blockquote."""
    return "\n".join(f"> {line}" if line else ">" for line in text.splitlines())


def docstring_blocks(obj: griffe.Object) -> Iterator[str]:
    """Render an object's parsed Google-style docstring as Markdown blocks."""
    if obj.docstring is None:
        return
    for section in obj.docstring.parsed:
        kind = section.kind
        if kind is griffe.DocstringSectionKind.text:
            yield str(section.value).strip()
        elif kind is griffe.DocstringSectionKind.examples:
            yield "**Examples:**"
            for _, example in section.value:
                yield str(example).strip()
        elif kind is griffe.DocstringSectionKind.admonition:
            title = section.title or "Note"
            yield quoted(f"**{title}:**\n{section.value.description.strip()}")
        elif kind is griffe.DocstringSectionKind.deprecated:
            yield quoted(f"**Deprecated:**\n{section.value.description.strip()}")
        elif kind in SECTION_HEADINGS:
            yield f"**{SECTION_HEADINGS[kind]}:**"
            yield "\n".join(item_lines(section.value))


def item_lines(items: Iterable[object]) -> Iterator[str]:
    """Render the entries of a typed docstring section as Markdown list items."""
    for item in items:
        name = getattr(item, "name", None)
        annotation = getattr(item, "annotation", None)
        description = " ".join((getattr(item, "description", "") or "").split())
        label = f"`{name}`" if name else ""
        if annotation is not None:
            label = f"{label} (`{annotation}`)" if label else f"`{annotation}`"
        yield f"- {label} — {description}" if label else f"- {description}"


def heading_blocks(obj: griffe.Object, *, level: int, label: str) -> Iterator[str]:
    """Yield the heading, source link, and docstring blocks shared by every entry."""
    yield f"{'#' * level} {label}"
    link = source_link(obj)
    if link:
        yield link
    yield from docstring_blocks(obj)


def function_blocks(func: griffe.Function, *, level: int) -> Iterator[str]:
    """Render a function or method entry."""
    prefix = "async " if "async" in func.labels else ""
    yield from heading_blocks(func, level=level, label=f"`{prefix}{func.name}{signature(func)}`")


def attribute_blocks(attribute: griffe.Attribute, *, level: int) -> Iterator[str]:
    """Render a documented module-level or class-level attribute."""
    annotation = f": {attribute.annotation}" if attribute.annotation is not None else ""
    yield from heading_blocks(attribute, level=level, label=f"`{attribute.name}{annotation}`")


def class_blocks(cls: griffe.Class, *, level: int) -> Iterator[str]:
    """Render a class entry with its public methods."""
    yield f"{'#' * level} `{cls.name}`"
    if cls.bases:
        yield "Bases: " + ", ".join(f"`{base}`" for base in cls.bases)
    link = source_link(cls)
    if link:
        yield link
    yield from docstring_blocks(cls)
    for member in members(cls):
        if isinstance(member, griffe.Function):
            yield from function_blocks(member, level=level + 1)


def module_blocks(module: griffe.Module, *, level: int) -> Iterator[str]:
    """Render a module with its classes, functions, and documented attributes."""
    yield from heading_blocks(module, level=level, label=f"`{module.path}`")
    for member in members(module):
        if isinstance(member, griffe.Class):
            yield from class_blocks(member, level=level + 1)
        elif isinstance(member, griffe.Function):
            yield from function_blocks(member, level=level + 1)
        elif isinstance(member, griffe.Attribute):
            yield from attribute_blocks(member, level=level + 1)


def walk_modules(module: griffe.Module) -> Iterator[griffe.Module]:
    """Yield a module and every public submodule beneath it, alphabetically."""
    yield module
    for name in sorted(module.members):
        member = module.members[name]
        if name.startswith("_") or not isinstance(member, griffe.Module):
            continue
        yield from walk_modules(member)


def render_page(page: Page, package: griffe.Module) -> str:
    """Render one complete reference page."""
    blocks = [
        f'---\ntitle: "{page.title}"\n---',
        GENERATED_MARKER,
        page.description,
    ]
    for path in page.modules:
        for module in walk_modules(resolve(package, path)):
            if not module.members and module.docstring is None:
                continue
            blocks.extend(module_blocks(module, level=2))
    return "\n\n".join(block.strip() for block in blocks if block.strip()) + "\n"


def main() -> int:
    """Write, or with ``--check`` verify, the generated reference pages."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed reference pages are stale",
    )
    arguments = parser.parse_args()

    package = load_package()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    for page in PAGES:
        destination = OUTPUT_DIR / f"{page.slug}.md"
        content = render_page(page, package)
        if arguments.check:
            current = destination.read_text(encoding="utf-8") if destination.exists() else ""
            if current != content:
                stale.append(str(destination.relative_to(ROOT)))
            continue
        destination.write_text(content, encoding="utf-8")
        print(f"wrote {destination.relative_to(ROOT)}")

    if stale:
        print("Generated API reference is stale; regenerate it with: just docs-api")
        for path in stale:
            print(f"  - {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
