# Generated by Django 5.2.10 on 2026-01-29 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micboard', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text="Unique setting key (e.g., 'battery_low_threshold')", max_length=255, unique=True)),
                ('label', models.CharField(help_text='Human-readable label for admin interface', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this setting controls')),
                ('scope', models.CharField(choices=[('global', 'Global (applies to all)'), ('organization', 'Organization (MSP mode)'), ('site', 'Site (multi-site mode)'), ('manufacturer', 'Manufacturer-specific')], default='global', help_text='Whether setting applies globally, per-org, per-site, or per-manufacturer', max_length=20)),
                ('setting_type', models.CharField(choices=[('string', 'Text'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('choices', 'Dropdown')], default='string', help_text='Data type for this setting', max_length=20)),
                ('default_value', models.TextField(help_text='Default value (stored as string)')),
                ('choices_json', models.JSONField(blank=True, default=dict, help_text='For TYPE_CHOICES: {value: label} mapping')),
                ('required', models.BooleanField(default=False, help_text='Whether this setting must be configured')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this setting without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setting Definition',
                'verbose_name_plural': 'Setting Definitions',
                'ordering': ['scope', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(blank=True, help_text='Organization ID if scope is ORGANIZATION', null=True)),
                ('manufacturer_id', models.IntegerField(blank=True, help_text='Manufacturer ID if scope is MANUFACTURER', null=True)),
                ('value', models.TextField(help_text='Setting value (stored as string, parsed by definition)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, help_text='Site if scope is SITE', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.site')),
                ('definition', models.ForeignKey(help_text='Which setting this defines', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='micboard.settingdefinition')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['definition', 'organization_id', 'site', 'manufacturer_id'],
                'unique_together': {('definition', 'organization_id', 'site', 'manufacturer_id')},
            },
        ),
    ]
