# Generated by Django 5.2.7 on 2025-10-20 21:40

"""Add discovery models for CIDR/FQDN and discovery job tracking.

This migration creates models used by the Shure discovery integration.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryCIDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(help_text='CIDR range (e.g., 10.0.0.0/22)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(help_text='Manufacturer this CIDR applies to', on_delete=django.db.models.deletion.CASCADE, to='micboard.manufacturer')),
            ],
            options={
                'verbose_name': 'Discovery CIDR',
                'verbose_name_plural': 'Discovery CIDRs',
                'ordering': ['manufacturer__name', 'cidr'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryFQDN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(help_text='FQDN or pattern (e.g., host.example.com)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(help_text='Manufacturer this FQDN applies to', on_delete=django.db.models.deletion.CASCADE, to='micboard.manufacturer')),
            ],
            options={
                'verbose_name': 'Discovery FQDN',
                'verbose_name_plural': 'Discovery FQDNs',
                'ordering': ['manufacturer__name', 'fqdn'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action (sync/scan)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('items_scanned', models.IntegerField(blank=True, null=True)),
                ('items_submitted', models.IntegerField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(help_text='Manufacturer this job relates to', on_delete=django.db.models.deletion.CASCADE, to='micboard.manufacturer')),
            ],
            options={
                'verbose_name': 'Discovery Job',
                'verbose_name_plural': 'Discovery Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
