# Generated by Django 5.1.15 on 2026-07-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micboard', '0002_settingdefinition_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='campus_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='Campus identifier for optional MSP isolation', null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='organization_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='Organization identifier for optional MSP isolation', null=True),
        ),
    ]
