# Generated by Django 5.2.7 on 2025-10-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micboard', '0002_charger_chargerslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmitter',
            name='charging_status',
            field=models.BooleanField(default=False, help_text='Whether the transmitter is currently charging'),
        ),
    ]
