# Generated by Django 5.2.7 on 2025-10-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micboard', '0003_transmitter_charging_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('sse', 'Server-Sent Events'), ('websocket', 'WebSocket')], help_text='Type of real-time connection', max_length=20)),
                ('status', models.CharField(choices=[('connecting', 'Connecting'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('stopped', 'Stopped')], default='disconnected', help_text='Current connection status', max_length=20)),
                ('connected_at', models.DateTimeField(blank=True, help_text='When the connection was established', null=True)),
                ('last_message_at', models.DateTimeField(blank=True, help_text='When the last message was received', null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, help_text='When the connection was lost', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Last error message if connection failed')),
                ('error_count', models.PositiveIntegerField(default=0, help_text='Number of consecutive connection errors')),
                ('last_error_at', models.DateTimeField(blank=True, help_text='When the last error occurred', null=True)),
                ('reconnect_attempts', models.PositiveIntegerField(default=0, help_text='Number of reconnection attempts')),
                ('max_reconnect_attempts', models.PositiveIntegerField(default=5, help_text='Maximum number of reconnection attempts before giving up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.OneToOneField(help_text='The receiver this connection is for', on_delete=django.db.models.deletion.CASCADE, related_name='realtime_connection', to='micboard.receiver')),
            ],
            options={
                'verbose_name': 'Real-Time Connection',
                'verbose_name_plural': 'Real-Time Connections',
                'indexes': [models.Index(fields=['status', 'connection_type'], name='micboard_re_status_2253a4_idx'), models.Index(fields=['receiver', 'status'], name='micboard_re_receive_780e20_idx'), models.Index(fields=['last_message_at'], name='micboard_re_last_me_16f490_idx')],
            },
        ),
    ]
