# Generated by Django 5.1.15 on 2026-07-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micboard', '0003_building_campus_id_building_organization_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturerapiserver',
            name='verify_ssl',
        ),
    ]
