# Generated by Django 5.2.8 on 2026-01-22 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('micboard', '0004_add_realtime_connection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique code for manufacturer (e.g., 'shure', 'sennheiser')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Shure Incorporated')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this manufacturer service is enabled')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Service-specific configuration as JSON')),
                ('validation_errors', models.JSONField(blank=True, default=dict, help_text='Validation errors from last check')),
                ('last_validated', models.DateTimeField(blank=True, help_text='Timestamp of last validation', null=True)),
                ('is_valid', models.BooleanField(default=False, help_text='Whether current configuration is valid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manufacturer Configuration',
                'verbose_name_plural': 'Manufacturer Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('validate', 'Validate'), ('apply', 'Apply'), ('test', 'Test')], help_text='Action performed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Previous configuration values')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New configuration values')),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', help_text='Result of the action', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('configuration', models.ForeignKey(help_text='Configuration that was changed', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='micboard.manufacturerconfiguration')),
            ],
            options={
                'verbose_name': 'Configuration Audit Log',
                'verbose_name_plural': 'Configuration Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('health_check', 'Health Check')], help_text='Type of sync', max_length=50)),
                ('started_at', models.DateTimeField(help_text='When sync started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When sync completed', null=True)),
                ('device_count', models.IntegerField(default=0, help_text='Total devices synced')),
                ('online_count', models.IntegerField(default=0, help_text='Devices that came online')),
                ('offline_count', models.IntegerField(default=0, help_text='Devices that went offline')),
                ('updated_count', models.IntegerField(default=0, help_text='Devices with updated data')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], help_text='Sync result', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional sync details')),
                ('service', models.ForeignKey(help_text='Manufacturer being synced', on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='micboard.manufacturer')),
            ],
            options={
                'verbose_name': 'Service Sync Log',
                'verbose_name_plural': 'Service Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('crud', 'CRUD Operation'), ('service', 'Service Activity'), ('sync', 'Device Sync'), ('config', 'Configuration'), ('discovery', 'Discovery'), ('alert', 'Alert')], db_index=True, default='crud', help_text='Type of activity', max_length=20)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('start', 'Start'), ('stop', 'Stop'), ('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning')], db_index=True, default='create', help_text='Operation performed', max_length=20)),
                ('service_code', models.CharField(blank=True, help_text='Service code (for service activities)', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the affected object', null=True)),
                ('summary', models.CharField(help_text='Brief summary of the activity', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed information as JSON')),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Previous values (for update operations)')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New values (for create/update operations)')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('warning', 'Warning')], db_index=True, default='success', help_text='Result status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if operation failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When activity occurred')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=255)),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the affected object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the activity (null for system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity_type', '-created_at'], name='micboard_ac_activit_e0c15e_idx'), models.Index(fields=['operation', '-created_at'], name='micboard_ac_operati_501e97_idx'), models.Index(fields=['user', '-created_at'], name='micboard_ac_user_id_33097c_idx'), models.Index(fields=['status', '-created_at'], name='micboard_ac_status_6b834a_idx'), models.Index(fields=['content_type', 'object_id'], name='micboard_ac_content_b67b53_idx'), models.Index(fields=['created_at'], name='micboard_ac_created_d9a358_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='manufacturerconfiguration',
            index=models.Index(fields=['code'], name='micboard_ma_code_88f0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturerconfiguration',
            index=models.Index(fields=['is_active'], name='micboard_ma_is_acti_03b921_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationauditlog',
            index=models.Index(fields=['configuration', '-created_at'], name='micboard_co_configu_187584_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationauditlog',
            index=models.Index(fields=['action'], name='micboard_co_action_4dcabd_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesynclog',
            index=models.Index(fields=['service', '-started_at'], name='micboard_se_service_a69f37_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesynclog',
            index=models.Index(fields=['status'], name='micboard_se_status_e0fdbd_idx'),
        ),
    ]
