# Generated by Django 5.1.15 on 2026-07-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micboard', '0004_remove_manufacturerapiserver_verify_ssl'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('manufacturer_id__isnull', True), ('organization_id__isnull', True), ('site__isnull', True)), models.Q(('manufacturer_id__isnull', True), ('organization_id__isnull', False), ('site__isnull', True)), models.Q(('manufacturer_id__isnull', True), ('organization_id__isnull', True), ('site__isnull', False)), models.Q(('manufacturer_id__isnull', False), ('organization_id__isnull', True), ('site__isnull', True)), _connector='OR'), name='setting_exactly_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(condition=models.Q(('manufacturer_id__isnull', True), ('organization_id__isnull', True), ('site__isnull', True)), fields=('definition',), name='setting_unique_global'),
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(condition=models.Q(('manufacturer_id__isnull', True), ('organization_id__isnull', False), ('site__isnull', True)), fields=('definition', 'organization_id'), name='setting_unique_organization'),
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(condition=models.Q(('manufacturer_id__isnull', True), ('organization_id__isnull', True), ('site__isnull', False)), fields=('definition', 'site'), name='setting_unique_site'),
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(condition=models.Q(('manufacturer_id__isnull', False), ('organization_id__isnull', True), ('site__isnull', True)), fields=('definition', 'manufacturer_id'), name='setting_unique_manufacturer'),
        ),
    ]
