# Generated by Django 5.2.8 on 2026-01-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micboard', '0005_manufacturerconfiguration_configurationauditlog_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='receiver',
            name='micboard_re_is_acti_7d55e8_idx',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='is_active',
        ),
        migrations.AddField(
            model_name='receiver',
            name='status',
            field=models.CharField(db_index=True, default='discovered', help_text='Current lifecycle status of the device', max_length=20),
        ),
        migrations.AddField(
            model_name='receiver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time this device record was updated'),
        ),
        migrations.AddField(
            model_name='transmitter',
            name='api_status',
            field=models.CharField(blank=True, help_text='Transmitter status from API', max_length=50),
        ),
        migrations.AddField(
            model_name='transmitter',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time this device was successfully polled', null=True),
        ),
        migrations.AlterField(
            model_name='transmitter',
            name='status',
            field=models.CharField(db_index=True, default='discovered', help_text='Current lifecycle status of the device', max_length=20),
        ),
        migrations.AddIndex(
            model_name='receiver',
            index=models.Index(fields=['status', 'last_seen'], name='micboard_re_status_4d54d0_idx'),
        ),
    ]
