name: Build Windows Shure System API Image

on:
  workflow_dispatch:
    inputs:
      installer_url:
        description: 'Optional: URL to the Shure System API installer'
        required: false
      installer_file:
        description: 'Optional: Installer filename (e.g. SystemAPI-Windows-6.6.0.exe)'
        required: false
      silent_args:
        description: 'Optional: Silent install args passed to installer (default: /S /quiet for EXE)'
        required: false

jobs:
  build-windows-image:
    name: Build Windows Image
    runs-on: windows-2025
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Windows Image
        run: |
          $installer_url = '${{ github.event.inputs.installer_url }}'
          $installer_file = '${{ github.event.inputs.installer_file }}'
          $silent_args = '${{ github.event.inputs.silent_args }}'

          $buildArgs = @()
          if ($installer_url -ne '') { $buildArgs += "--build-arg SHURE_INSTALLER_URL=$installer_url" }
          if ($installer_file -ne '') { $buildArgs += "--build-arg SHURE_INSTALLER_FILE=$installer_file" }
          if ($silent_args -ne '') { $buildArgs += "--build-arg SHURE_INSTALLER_SILENT_ARGS=$silent_args" }

          $buildArgString = $buildArgs -join ' '

          docker build $buildArgString -t micboard/shure-system-api:windows demo/windows

      - name: Push (Optional)
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        run: |
          docker push micboard/shure-system-api:windows

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: windows-image-built
          path: |
            demo/windows/Dockerfile
            demo/windows/entrypoint.ps1
