name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Update version to CalVer
      run: |
        VERSION=$(date +%y.%m.%d)
        echo "Updating version to $VERSION"
        sed -i "s/__version__ = '.*'/__version__ = '$VERSION'/" micboard/__init__.py
        sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
        sed -i "s/return '.*'/return '$VERSION'/" setup.py
        sed -i "s/@v.*\"/@v$VERSION\"/" README.md

    - name: Check package
      run: twine check dist/*

    - name: Publish to Test PyPI
      if: github.event_name == 'workflow_dispatch'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        twine upload --repository testpypi dist/*

    - name: Publish to PyPI
      if: github.event_name == 'release'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*

    - name: Publish to GitHub Packages
      env:
        TWINE_USERNAME: ${{ github.actor }}
        TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        TWINE_REPOSITORY_URL: https://pypi.pkg.github.com/justprosound
      run: |
        twine upload --repository-url https://pypi.pkg.github.com/justprosound dist/*
