name: Release Drafter
run-name: "Release Drafter · ${{ github.head_ref || github.ref_name }}"

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  update_release_draft:
    name: Update Release Draft
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348  # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
