name: Release Drafter
run-name: "Release Drafter · ${{ github.head_ref || github.ref_name }}"

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  update_release_draft:
    name: Update Release Draft
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up uv and Python
        uses: ./.github/actions/setup-uv-python
        with:
          enable-cache: "false"

      - name: Calculate next CalVer
        id: calver
        run: |
          uv tool run bump-my-version bump patch
          VERSION="$(grep '^version = ' pyproject.toml | cut -d '\"' -f 2)"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - uses: release-drafter/release-drafter@eada3c96a64734dd381cfbda23511034e328ddb0  # v7
        with:
          name: v${{ steps.calver.outputs.version }}
          tag: v${{ steps.calver.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
